const express = require('express')
const router = express.Router();
const controller = require('../../controllers/client/user-controller')
const validate = require('../../validate/client/user-validate')
const authMiddleware = require('../../middlewares/client/auth-middleware')
const uploadCloud = require('../../middlewares/client/fileupload-middleware')
const multer = require('multer')
const upload = multer();

router.get('/register', controller.getRegister)
router.post('/check-register', validate.checkRegister, controller.checkRegister)
router.get('/login', controller.getLogin)
router.post('/login', validate.checkLogin, controller.postLogin)
router.get('/logout', controller.getLogout)
router.get('/password/forgot', controller.getForgotPassword)
router.post('/password/forgot', controller.postForgotPassword)
router.get('/password/otp', controller.getOTPPassword)
router.post('/password/otp', controller.postOTPPassword)
router.get('/password/reset', authMiddleware.checkReset, controller.getResetPassword)
router.post('/password/reset', authMiddleware.checkReset, validate.checkConfirmPassword, controller.postResetPassword)
router.get('/info', upload.single('avatar'), uploadCloud.upload, authMiddleware.checkLogin, controller.getInfo)
router.get('/info/edit', authMiddleware.checkLogin, controller.getEditInfo)
router.patch('/info/edit', authMiddleware.checkLogin, upload.single('avatar'), uploadCloud.upload, validate.checkEditUser, controller.patchInfoEdit)
router.get('/validate-account/otp', controller.getValidateOTP)
router.post('/validate-account/otp', controller.postValidateOTP)
module.exports = router